"""Changed map id to string.

Revision ID: 1aa2185dfade
Revises: b0334a675251
Create Date: 2024-03-16 11:26:00.114702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1aa2185dfade'
down_revision = 'b0334a675251'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookable', schema=None) as batch_op:
        batch_op.alter_column('map_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookable', schema=None) as batch_op:
        batch_op.alter_column('map_id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
