"""Changed foreign key for bookable

Revision ID: 751682d55494
Revises: 7745e1f793cd
Create Date: 2024-03-15 18:59:08.155798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '751682d55494'
down_revision = '7745e1f793cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_constraint('booking_bookable_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'bookable', ['bookable_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('booking_bookable_id_fkey', 'room', ['bookable_id'], ['id'])

    # ### end Alembic commands ###
