"""Changed database schema.

Revision ID: 7745e1f793cd
Revises: 92ceda2d502a
Create Date: 2024-03-15 17:26:26.204959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7745e1f793cd'
down_revision = '92ceda2d502a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookable', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(), nullable=False))

    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bookable_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('booking_room_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'room', ['bookable_id'], ['id'])
        batch_op.drop_column('id')
        batch_op.drop_column('room_id')

    with op.batch_alter_table('desk', schema=None) as batch_op:
        batch_op.add_column(sa.Column('number_available', sa.Integer(), nullable=False))
        batch_op.drop_constraint('desk_bookable_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'bookable', ['id'], ['id'])
        batch_op.drop_column('bookable_id')

    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.drop_constraint('room_bookable_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'bookable', ['id'], ['id'])
        batch_op.drop_column('bookable_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bookable_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('room_bookable_id_fkey', 'bookable', ['bookable_id'], ['id'])

    with op.batch_alter_table('desk', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bookable_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('desk_bookable_id_fkey', 'bookable', ['bookable_id'], ['id'])
        batch_op.drop_column('number_available')

    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('room_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('booking_room_id_fkey', 'room', ['room_id'], ['id'])
        batch_op.drop_column('bookable_id')

    with op.batch_alter_table('bookable', schema=None) as batch_op:
        batch_op.drop_column('type')

    # ### end Alembic commands ###
