"""Added accepted to booking, supporting mmultiple people in a room.

Revision ID: 7f8a48441af0
Revises: ea325fc8b74d
Create Date: 2024-03-16 18:42:51.374535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f8a48441af0'
down_revision = 'ea325fc8b74d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('accepted', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_column('accepted')

    # ### end Alembic commands ###
