"""fixed enum in migration script

Revision ID: 92ceda2d502a
Revises: a15bddf2b3c2
Create Date: 2024-03-15 16:48:52.490061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92ceda2d502a'
down_revision = 'a15bddf2b3c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('map_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('map_id')
    )
    op.create_table('desk',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bookable_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bookable_id'], ['bookable.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('room',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bookable_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bookable_id'], ['bookable.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('booking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('start', sa.Time(), nullable=False),
    sa.Column('end', sa.Time(), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['room.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('booking')
    op.drop_table('room')
    op.drop_table('desk')
    op.drop_table('bookable')
    # ### end Alembic commands ###
