"""initial db model

Revision ID: a15bddf2b3c2
Revises: c5f4c131a25c
Create Date: 2024-03-15 16:20:07.955008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a15bddf2b3c2'
down_revision = 'c5f4c131a25c'
branch_labels = None
depends_on = None


def upgrade():
    # Create the enum type 'user_role_enum'
    op.execute("CREATE TYPE user_role_enum AS ENUM ('admin', 'employee')")

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('password', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('username', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('role', sa.Enum('admin', 'employee', name='user_role_enum'), nullable=False,
                                      server_default='employee'))
        batch_op.create_unique_constraint(None, ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('role')
        batch_op.drop_column('username')
        batch_op.drop_column('password')
        batch_op.drop_column('email')

    # Drop the enum type 'user_role_enum'
    op.execute("DROP TYPE user_role_enum")

    # ### end Alembic commands ###
