"""Added capacity to rooms.

Revision ID: b0334a675251
Revises: 452ab9639032
Create Date: 2024-03-16 11:10:22.601055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0334a675251'
down_revision = '452ab9639032'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('desk', schema=None) as batch_op:
        batch_op.drop_column('number_available')

    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.add_column(sa.Column('capacity', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.drop_column('capacity')

    with op.batch_alter_table('desk', schema=None) as batch_op:
        batch_op.add_column(sa.Column('number_available', sa.INTEGER(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
