"""Made map_id not unique and nullable.

Revision ID: ea325fc8b74d
Revises: 1aa2185dfade
Create Date: 2024-03-16 11:27:54.865698

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea325fc8b74d'
down_revision = '1aa2185dfade'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookable', schema=None) as batch_op:
        batch_op.alter_column('map_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.drop_constraint('bookable_map_id_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookable', schema=None) as batch_op:
        batch_op.create_unique_constraint('bookable_map_id_key', ['map_id'])
        batch_op.alter_column('map_id',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
